"""add deadline and priority to def create_task

Revision ID: 344a42c05ec4
Revises: dd9bf7493dab
Create Date: 2026-03-30 14:03:18.547650
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = '344a42c05ec4'
down_revision: Union[str, None] = 'dd9bf7493dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
