"""add def delete_task and def delete_tag

Revision ID: 3518a773b57a
Revises: 590ece40a099
Create Date: 2026-03-30 19:14:19.973558
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = '3518a773b57a'
down_revision: Union[str, None] = '590ece40a099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
