"""add def delete_user and def delete_project

Revision ID: 590ece40a099
Revises: 344a42c05ec4
Create Date: 2026-03-30 15:05:20.635424
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = '590ece40a099'
down_revision: Union[str, None] = '344a42c05ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
