"""add deadline and priority to task

Revision ID: b280ee5f8c4d
Revises: c218287a7be9
Create Date: 2026-03-30 12:43:18.755061
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = 'b280ee5f8c4d'
down_revision: Union[str, None] = 'c218287a7be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    op.drop_column('task', 'deadline')
    # ### end Alembic commands ###
