"""add description to def create_project

Revision ID: b94314ad4642
Revises: d3af11bb869d
Create Date: 2026-03-30 20:05:45.171860
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = 'b94314ad4642'
down_revision: Union[str, None] = 'd3af11bb869d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
