"""add is_active to project

Revision ID: dd9bf7493dab
Revises: b280ee5f8c4d
Create Date: 2026-03-30 13:36:28.897825
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = 'dd9bf7493dab'
down_revision: Union[str, None] = 'b280ee5f8c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_active')
    # ### end Alembic commands ###
